name: Mend UA Release Scan

on:
  push:
    branches:
    - '**release**'

jobs:
  call-java-prioritize:
    uses: WFS-Mend/whitesource-config/.github/workflows/java_prioritize.yml@main
    with:
      mvn-cmd: 'mvn deploy -s ./.github/workflows/settings.xml'
    secrets: inherit
